from __future__ import annotations

from typing import Dict

from .skill_models import SkillSpec, utility_provider_spec

UTILITY_PROVIDER_SKILLS: Dict[str, SkillSpec] = {
    "research": utility_provider_spec(
        name="research",
        description="Use when a hub needs fresh evidence but should retain ownership of the lane. Stateless research utility for product, market, technical, or domain questions.",
        outputs=[
            "evidence bullets appended to the active artifact",
            "assumption checks or citations for the current decision",
            "a short list of unresolved questions only when they block the next decision",
        ],
        references=["Do not own the plan; feed findings back to the current hub.", "Prefer current evidence over generic opinions."],
        next_steps=["brainstorm-hub", "plan-hub", "workflow-router"],
        mission="Gather the minimum useful research needed for the next decision, then hand control back immediately.",
        tasks=[
            "Answer the current decision question, not the whole topic.",
            "Summarize only the market, technical, or domain evidence that changes the next move.",
            "Mark which assumptions are confirmed, unconfirmed, or contradicted.",
            "Recommend the smallest next question only when uncertainty still blocks the lane.",
        ],
        rules=[
            "Write into `product-brief.md`, `PRD.md`, or the active artifact instead of creating a side quest.",
            "Separate evidence from recommendation.",
            "Name the source, provenance, and freshness whenever possible.",
            "Stop as soon as the owning hub can decide without another broad research pass.",
        ],
    ),
    "doc-pointers": utility_provider_spec(
        name="doc-pointers",
        description="Use when a hub needs exact docs fragments, file paths, or source references before deciding. Stateless docs retrieval utility.",
        outputs=[
            "doc pointers, file paths, or citations appended to the active artifact",
            "a short conflict note when documentation and implementation disagree",
        ],
        references=["Return exact doc pointers, not vague summaries.", "Prefer repo-local docs and code comments before broader sources when the task is codebase-specific."],
        next_steps=["scout-hub", "review-hub", "workflow-router"],
        mission="Find the smallest set of authoritative documentation fragments needed to unblock the lane.",
        tasks=[
            "Check repo-local docs, comments, and nearby code first when the question is codebase-specific.",
            "Locate the smallest authoritative fragment that answers the current question.",
            "Return exact file paths, anchors, or section names whenever possible.",
            "Flag contradictions between docs and implementation instead of smoothing them over.",
        ],
        rules=[
            "Citations and file paths are more valuable than long summaries.",
            "Quote or summarize only the load-bearing fragment.",
            "Format the result so the owning hub can paste it straight into the active artifact.",
            "Stop once the next skill has enough exact evidence to act safely.",
        ],
    ),
    "sequential-thinking": utility_provider_spec(
        name="sequential-thinking",
        description="Use when a hub needs structured thought without changing ownership. Stepwise reasoning utility for debugging, planning, or decomposition.",
        outputs=["ordered reasoning steps added to investigation-notes or the active artifact"],
        references=["Break work into explicit steps and checkpoints.", "Reasoning should support a decision, not become the decision owner."],
        next_steps=["debug-hub", "plan-hub", "fix-hub"],
        mission="Turn a messy question into a short sequence of evidence-backed steps.",
        tasks=["Decompose the problem into checkpoints.", "Identify what must be known before acting.", "Recommend the next most informative test or observation."],
        rules=["Keep the sequence short and testable.", "Tie each step to an artifact or evidence source.", "Do not claim completion for the lane."],
    ),
    "problem-solving": utility_provider_spec(
        name="problem-solving",
        description="Use when a hub needs hypotheses, trade-offs, or resolution paths grounded in current evidence. Option-generation and root-cause utility.",
        outputs=["options, hypotheses, and trade-offs appended to the active artifact"],
        references=["Root cause beats guess-and-patch.", "Surface trade-offs before implementation starts."],
        next_steps=["debug-hub", "plan-hub", "review-hub"],
        mission="Turn evidence into plausible options and ranked next moves.",
        tasks=["Generate root-cause hypotheses.", "Compare implementation or mitigation options.", "Call out the cheapest validating experiment."],
        rules=["Ground every option in evidence already collected.", "State uncertainty instead of bluffing.", "Recommend escalation if the issue is really a planning problem."],
    ),
    "intent-lock": utility_provider_spec(
        name="intent-lock",
        description="Use when a request includes edits and the lane must lock what is allowed versus forbidden before implementation or media transformations begin.",
        outputs=[
            "intent-contract entries with allowed, forbidden, and done-signal clauses appended to the active artifact set",
            "workflow-state intent-lock status update with required and pass or hold result",
        ],
        references=[
            "A completion claim is invalid when intent lock is missing for edit requests.",
            "Use explicit allowed and forbidden language instead of broad summaries.",
        ],
        next_steps=["entity-lock", "fix-hub", "test-hub", "review-hub", "workflow-router"],
        mission="Convert user intent into a machine-checkable scope lock before any edit work proceeds.",
        tasks=[
            "Restate the user request in one sentence without introducing new goals.",
            "List allowed changes, forbidden changes, and expected done signal.",
            "Name target objects and mark unresolved ambiguity as hold.",
            "Update workflow-state intent-lock fields so downstream gates can enforce consistently.",
        ],
        rules=[
            "Do not allow implementation to proceed when allowed and forbidden boundaries are missing.",
            "If request intent is ambiguous, return hold instead of guessing.",
            "Keep scope lock minimal and specific to the active lane.",
        ],
    ),
    "entity-lock": utility_provider_spec(
        name="entity-lock",
        description="Use when media or UI edits involve multiple similar entities and each editable target must be identified with stable IDs.",
        outputs=[
            "entity-map with stable IDs and allowed or forbidden edit scope appended to the active artifact set",
            "workflow-state entity-lock status update with pass or hold result",
        ],
        references=[
            "Media or UI edits must not proceed when entity boundaries are ambiguous.",
            "Entity IDs should be stable and human-auditable, such as P1, P2, UI-1.",
        ],
        next_steps=["multimodal-evidence", "media-tooling", "prompt-fidelity-check", "test-hub", "review-hub"],
        mission="Prevent wrong-target edits by locking entity IDs and exact edit boundaries before transformations run.",
        tasks=[
            "Assign stable IDs to each target and nearby non-target entities.",
            "Map each ID to allowed edit scope and forbidden edit scope.",
            "Record ambiguous regions that require confirmation before editing.",
            "Update workflow-state entity-lock fields for downstream enforcement.",
        ],
        rules=[
            "If entity identity is uncertain, return hold and do not continue edits.",
            "Do not treat unnamed groups as safe targets.",
            "Keep entity map aligned with intent-contract boundaries.",
        ],
    ),
    "multimodal-evidence": utility_provider_spec(
        name="multimodal-evidence",
        description="Use when screenshots, diagrams, rendered UIs, or media artifacts contain important clues and entity-level lock evidence is needed.",
        outputs=["visual or media observations with entity-level notes appended to the active artifact"],
        references=["Describe what is visible and why it matters.", "Feed observations back to the owning hub."],
        next_steps=["entity-lock", "prompt-fidelity-check", "debug-hub", "test-hub", "review-hub"],
        mission="Translate visual or media evidence into concrete observations that preserve target-entity boundaries.",
        tasks=[
            "Inspect screenshots, diagrams, or logs embedded as images.",
            "Summarize what changed between before and after artifacts with target IDs.",
            "Call out ambiguous areas that require entity-lock hold before editing continues.",
        ],
        rules=[
            "Do not over-interpret weak signals.",
            "Tie observations to UI states, logs, acceptance criteria, and target IDs.",
            "If entity identity is ambiguous, route to entity-lock and hold edits.",
        ],
    ),
    "browser-inspector": utility_provider_spec(
        name="browser-inspector",
        description="Use when the active hub needs console, network, DOM, or performance observations from a web flow. Browser evidence utility.",
        outputs=["browser-side evidence appended to investigation-notes or qa-report"],
        references=["Collect evidence first, then suggest the next move.", "Capture the smallest reproducible browser path."],
        next_steps=["debug-hub", "test-hub", "review-hub"],
        mission="Collect browser-native evidence that narrows a web issue fast.",
        tasks=["Inspect console, network, layout, and performance clues.", "Note the exact page state and reproduction path.", "Return the evidence to the owning hub."],
        rules=["Prefer reproducible steps and specific requests over general browsing notes.", "Link evidence to the failing acceptance criterion or symptom.", "Do not claim the fix; supply the evidence."],
    ),
    "repo-map": utility_provider_spec(
        name="repo-map",
        description="Use when a hub needs a quick dependency map, file tree slice, or entrypoint overview before acting. Repo-map utility.",
        outputs=[
            "repo map notes appended to project-context or architecture",
            "a short read-first file list for the next skill",
        ],
        references=["Good for unfamiliar areas and dependency direction.", "Use it to orient the lane, not to replace design thinking."],
        next_steps=["scout-hub", "plan-hub", "review-hub"],
        mission="Produce a compact map of the code area the lane is about to touch.",
        tasks=[
            "Scope the map to the area the lane is actually about to touch.",
            "List key entrypoints, modules, and dependency direction.",
            "Highlight likely impact surface (upstream callers, downstream dependencies, test touch points) when symbols are known.",
            "Highlight hotspots, choke points, or ownership boundaries.",
            "Name the first files the next skill should read instead of dumping the whole tree.",
        ],
        rules=[
            "Prefer repo-relative paths, modules, and boundaries over prose-heavy summaries.",
            "Prefer token-efficient map output over long narrative so the next skill can act in one pass.",
            "Keep the map small enough for the next skill to use immediately.",
            "If ownership is fuzzy, say so explicitly instead of inventing structure.",
            "If mapping data looks stale, mark it and route to scout-hub or index refresh before high-risk edits.",
            "Stop once the next skill can navigate without another broad repo walk.",
        ],
    ),
    "memory-search": utility_provider_spec(
        name="memory-search",
        description="Use when a hub needs past decisions, handoff breadcrumbs, or prior debug evidence from .relay-kit artifacts. Read-only state retrieval utility.",
        outputs=[
            "matching evidence excerpts from .relay-kit/state or .relay-kit/contracts appended to the active artifact",
            "a short continuity note that links current work to prior decisions",
        ],
        references=[
            "Prefer read-only retrieval from authoritative artifacts over replaying chat memory.",
            "Use `python scripts/memory_search.py <project> --query ...` for deterministic lookups.",
            "Use intent/path/freshness filters to return high-signal context in one pass instead of broad dumps.",
        ],
        next_steps=["debug-hub", "review-hub", "plan-hub", "workflow-router"],
        mission="Recover prior context quickly so the lane can reuse proven decisions and avoid repeating old mistakes.",
        tasks=[
            "Search `.relay-kit/state` and `.relay-kit/contracts` for the exact decision, failure pattern, or handoff being referenced.",
            "Use intent-aware retrieval when the lane needs decision, handoff, debug, review, or migration evidence.",
            "Return file paths and line-level excerpts that the active hub can verify immediately.",
            "Call out conflicts between older decisions and the current request instead of smoothing them over.",
            "Extract only the evidence needed for the next decision and stop.",
        ],
        rules=[
            "Stay read-only; do not rewrite artifacts during retrieval.",
            "Mark stale hits explicitly instead of mixing stale and fresh evidence silently.",
            "Cite concrete paths and lines, not vague summaries.",
            "Separate observed facts from interpretation when prior context is noisy.",
            "If no evidence is found, say so explicitly and route to fresh investigation instead of guessing.",
        ],
    ),
    "release-readiness": utility_provider_spec(
        name="release-readiness",
        description="Use when a lane needs a pre-deploy or post-deploy readiness verdict with explicit smoke signals and rollback guardrails.",
        outputs=[
            "release-readiness checklist notes appended to qa-report or workflow-state",
            "explicit go, hold, or rollback recommendation tied to machine-checkable signals",
        ],
        references=[
            "Use `python scripts/release_readiness.py <project> --phase pre|post` for deterministic checklists and signal evaluation.",
            "Treat `ready-check` as review readiness, not automatic production readiness.",
        ],
        next_steps=["test-hub", "review-hub", "qa-governor", "workflow-router"],
        mission="Convert release confidence into concrete pre and post deploy evidence instead of relying on optimistic completion claims.",
        tasks=[
            "Run a pre-deploy gate for build, tests, migration risk, and rollback plan status.",
            "Run a post-deploy smoke gate for health, error budget, and critical path behavior.",
            "Record which checks are observed, inferred, or still missing.",
            "Escalate hold or rollback when a critical signal fails.",
        ],
        rules=[
            "No go recommendation without machine-checkable evidence for critical signals.",
            "Keep pre and post deploy verdicts separate to avoid false confidence.",
            "If evidence is incomplete, return hold by default and list the exact missing signals.",
            "Document rollback trigger thresholds before calling a deploy safe.",
        ],
    ),
    "accessibility-review": utility_provider_spec(
        name="accessibility-review",
        description="Use when frontend work needs an explicit accessibility gate before merge, release, or completion claims.",
        outputs=[
            "accessibility gate findings appended to qa-report or review notes",
            "pass or hold verdict tied to keyboard, semantics, focus, and contrast evidence",
        ],
        references=[
            "Use `python scripts/accessibility_review.py <project>` to generate or evaluate the gate checklist.",
            "Treat accessibility as a required quality bar, not cosmetic polish.",
        ],
        next_steps=["test-hub", "review-hub", "qa-governor", "fix-hub"],
        mission="Turn accessibility from implicit best effort into a concrete review gate with machine-checkable status.",
        tasks=[
            "Check keyboard navigation, visible focus, semantic structure, labels, and contrast before claiming readiness.",
            "Record critical failures and map each one to affected screen or component paths.",
            "Return a hold verdict when critical accessibility evidence is missing.",
            "Hand unresolved findings back to fix-hub with explicit acceptance criteria.",
        ],
        rules=[
            "No pass verdict without evidence for all critical checks.",
            "Do not collapse accessibility into generic UI comments.",
            "Keep findings actionable: component, behavior, impact, and expected fix.",
            "If manual verification is needed, say exactly what to test and why.",
        ],
    ),
    "skill-gauntlet": utility_provider_spec(
        name="skill-gauntlet",
        description="Use when runtime skill behavior may have drifted and you need a regression gate before trusting routing or completion claims.",
        outputs=[
            "skill behavior regression findings appended to qa-report or workflow-state",
            "explicit pass or hold verdict for SKILL.md trigger and structure discipline",
        ],
        references=[
            "Use `python scripts/skill_gauntlet.py <project> --strict` for machine-checkable gating.",
            "Run this before promoting large skill edits, bundle changes, or release branches.",
        ],
        next_steps=["review-hub", "qa-governor", "workflow-router", "fix-hub"],
        mission="Protect routing quality by detecting skill drift early instead of waiting for behavior regressions in live lanes.",
        tasks=[
            "Validate SKILL.md frontmatter, trigger descriptions, and required section structure across runtime surfaces.",
            "Report malformed or stale skill files with concrete paths and checks.",
            "Gate release or migration work when skill quality checks fail.",
            "Hand failures to fix-hub with exact remediation targets.",
        ],
        rules=[
            "Treat skill behavior regressions as release risk, not optional cleanup.",
            "Prefer deterministic checks over subjective style review.",
            "Fail fast when trigger wording or core sections drift from required structure.",
            "Keep the gauntlet report small and path-specific so fixes are easy to apply.",
        ],
    ),
    "impact-radar": utility_provider_spec(
        name="impact-radar",
        description="Use when planning or review needs explicit blast-radius analysis before touching runtime, adapters, templates, or release-sensitive surfaces.",
        outputs=[
            "impact-area and changed-file breakdown appended to workflow-state or review notes",
            "risk level plus recommended verification gates for the current diff",
        ],
        references=[
            "Use `python scripts/impact_radar.py <project>` for deterministic working-tree analysis.",
            "Use `--base` and `--head` when the lane needs commit-range impact evidence for review.",
        ],
        next_steps=["plan-hub", "review-hub", "qa-governor", "workflow-router"],
        mission="Make change blast radius explicit before merge so gate selection is evidence-based instead of guess-based.",
        tasks=[
            "Classify changed files into runtime, adapter, scripts, templates, docs, and packaging impact areas.",
            "Return a compact risk level with the concrete reason it was assigned.",
            "Recommend the smallest gate set that still protects migration and runtime safety.",
            "Highlight high-impact areas that need additional manual review before merge.",
        ],
        rules=[
            "Use file-based evidence from git diff or working tree status; avoid speculative risk claims.",
            "Keep recommendations command-ready so the owning hub can execute immediately.",
            "Do not approve merges; provide impact evidence and required gates.",
            "Escalate to review-hub or qa-governor when impact spans runtime-core and adapter surfaces.",
        ],
    ),
    "runtime-doctor": utility_provider_spec(
        name="runtime-doctor",
        description="Use when runtime integrity may have drifted and you need deterministic diagnostics over adapters, artifacts, and lane state surfaces.",
        outputs=[
            "runtime drift findings with exact surface references appended to qa-report or workflow-state",
            "pass or hold recommendation for runtime health based on parity and artifact checks",
        ],
        references=[
            "Use `python scripts/runtime_doctor.py <project> --strict` for deterministic runtime diagnostics.",
            "Use `--state-mode live` when validating active project state artifacts before release claims.",
        ],
        next_steps=["debug-hub", "test-hub", "review-hub", "fix-hub"],
        mission="Catch adapter parity and runtime artifact drift early so regressions are blocked before release or cutover batches.",
        tasks=[
            "Verify required runtime docs and state artifacts exist under `.relay-kit`.",
            "Check adapter skill parity against canonical registry skills across `.claude`, `.agent`, and `.codex` surfaces.",
            "Flag missing, extra, or drifted skills with exact adapter paths.",
            "In live mode, detect stale placeholder state markers that invalidate readiness claims.",
        ],
        rules=[
            "Keep findings deterministic and path-specific so reruns are comparable.",
            "Distinguish template diagnostics from live runtime diagnostics in the final report.",
            "Do not auto-fix runtime drift; hand actionable findings back to fix-hub.",
            "Return hold when strict checks fail on parity or required artifacts.",
        ],
    ),
    "migration-guard": utility_provider_spec(
        name="migration-guard",
        description="Use when a migration or naming cutover might leave stale compatibility tokens behind. Enforce token-level cutover policy with an explicit allowlist gate.",
        outputs=[
            "cutover token drift findings appended to qa-report or workflow-state",
            "explicit pass or hold verdict for migration safety before merge",
        ],
        references=[
            "Use `python scripts/migration_guard.py <project> --strict` as the canonical migration gate.",
            "Only historical records and approved compatibility notes should be allowlisted.",
        ],
        next_steps=["test-hub", "review-hub", "qa-governor", "fix-hub"],
        mission="Block high-risk migration drift by proving old compatibility markers are gone from active runtime surfaces.",
        tasks=[
            "Scan source and runtime files for blocked compatibility tokens.",
            "Flag every non-allowlisted occurrence with file, line, and token evidence.",
            "Hold the lane when findings exist in active runtime or gate paths.",
            "Hand actionable findings back to fix-hub with exact cleanup targets.",
        ],
        rules=[
            "Do not hide active runtime drift behind broad allowlist rules.",
            "Treat allowlist as historical exception management, not a bypass for unfinished migration work.",
            "Run migration-guard before merge on every cutover batch touching runtime names or paths.",
            "Keep findings deterministic so repeated runs produce stable verdicts.",
        ],
    ),
    "context-continuity": utility_provider_spec(
        name="context-continuity",
        description="Use when work needs reliable continuity across long chats, new threads, AI switches, or resume-after-gap sessions.",
        outputs=[
            "checkpoint, rehydrate, handoff, or diff artifacts under .relay-kit/state and .relay-kit/handoffs",
            "a compact resume brief with explicit next step and open loops",
        ],
        references=[
            "Use `python scripts/context_continuity.py` modes for deterministic continuity artifacts.",
            "Context continuity complements `handoff-context`; it does not replace authoritative contracts and state.",
        ],
        next_steps=["workflow-router", "cook", "team", "handoff-context", "review-hub"],
        mission="Preserve lane continuity with explicit artifacts so the next session can continue safely without replaying full chat history.",
        tasks=[
            "Run checkpoint before likely truncation, compaction, or session break.",
            "Run rehydrate at the start of a new thread to restore objective, lane, blockers, and next step.",
            "Run handoff when ownership moves across AI, thread, or operator.",
            "Run diff-since-last to detect drift from the most recent checkpoint snapshot.",
        ],
        rules=[
            "Separate observed evidence from inferred context in all continuity outputs.",
            "Do not call continuity complete if next step, blockers, and evidence pointers are missing.",
            "Treat continuity artifacts as append-first records; avoid destructive rewrites.",
            "If continuity conflicts with current repo reality, escalate through workflow-router before coding.",
        ],
    ),
    "handoff-context": utility_provider_spec(
        name="handoff-context",
        description="Use when the next skill needs a tighter, more relevant context handoff than the current artifact already provides. Context-pack utility.",
        outputs=[
            "focused context pack notes added to workflow-state, story, or handoff-log",
            "an explicit include/exclude list for the receiving skill",
        ],
        references=[
            "Minimize irrelevant context.",
            "Package only what the receiving skill needs to act safely.",
            "Use context-continuity when the handoff must survive thread, model, or session boundaries.",
        ],
        next_steps=["workflow-router", "team", "cook", "developer", "context-continuity"],
        mission="Prepare the smallest complete context pack for the next handoff.",
        tasks=[
            "Select the minimum set of files, artifacts, and rules the receiving skill actually needs.",
            "Include impact-critical dependencies and known risk edges so the receiver does not rediscover blast radius.",
            "State why each included item matters.",
            "Name what was deliberately excluded and why it is safe to ignore for now.",
            "Write a short receiving-skill brief so the next handoff starts cleanly.",
        ],
        rules=[
            "Context quality beats context quantity.",
            "Use authoritative artifacts over memory.",
            "Update handoff-log when the receiving skill changes.",
            "Call out stale context explicitly before handoff completion.",
            "Stop when the receiving skill can act without reopening the whole repo or replaying the whole chat.",
            "Escalate to context-continuity when the receiving lane needs durable checkpoint and rehydrate artifacts.",
        ],
    ),
    "mermaid-diagrams": utility_provider_spec(
        name="mermaid-diagrams",
        description="Use when architecture, flow, or sequencing should be expressed as a quick mermaid diagram inside an artifact. Diagramming utility.",
        outputs=["mermaid snippets inserted into architecture, project-context, or docs"],
        references=["Prefer diagrams that clarify ownership, flow, or sequencing.", "Diagrams should serve the artifact, not replace it."],
        next_steps=["plan-hub", "architect", "review-hub"],
        mission="Make complex flow or structure easier to reason about with a compact diagram.",
        tasks=["Draw module boundaries or request flows.", "Show sequence or state transitions.", "Keep the diagram synchronized with the surrounding text."],
        rules=["Use only the detail level needed for the current decision.", "Avoid giant diagrams.", "Explain trade-offs in text when the diagram alone is insufficient."],
    ),
    "ux-structure": utility_provider_spec(
        name="ux-structure",
        description="Use when a hub needs sharper information hierarchy, cleaner flows, stronger screen structure, less generic AI-looking UI, or concrete UX corrections tied to implementation reality. UX and layout utility for user-facing work.",
        outputs=[
            "ux notes appended to product-brief, PRD, architecture, or qa-report",
            "recommended taste controls for design variance, motion intensity, and visual density",
            "state coverage notes for loading, empty, and error handling when the surface is real product UI",
        ],
        references=[
            "Use this skill to block AI-slop layouts, not merely to polish them.",
            "Prefer reference-driven direction, explicit hierarchy, and deliberate grid structure over generic SaaS template patterns.",
            "Return notes to the owning hub rather than taking over the project.",
        ],
        next_steps=["brainstorm-hub", "plan-hub", "review-hub"],
        mission="Sharpen hierarchy, flow, and design taste without stealing ownership from product or implementation lanes.",
        tasks=[
            "Outline the user journey or interaction flow.",
            "Set design variance, motion intensity, and visual density for the current slice before recommending layout changes.",
            "Call out friction, edge cases, copy issues, and template-like structure.",
            "Require loading, empty, and error states when the surface is a real product flow.",
            "Replace generic three-card layouts, filler gradients, and flex-hack compositions with stronger structure.",
        ],
        rules=[
            "Tie UX comments to a specific screen or step.",
            "Balance UX gains with implementation cost.",
            "Keep notes focused on the current slice.",
            "Do not approve purple-blue gradient filler, three-equal-card SaaS layouts, or layout choices that feel obviously AI-generated.",
            "Prefer grid layout or deliberate asymmetry over flex hacks when hierarchy matters.",
            "Keep motion performance-safe: prefer transform and opacity, and respect reduced-motion needs.",
        ],
    ),
    "media-tooling": utility_provider_spec(
        name="media-tooling",
        description="Use when screenshots, assets, or content files need transformation or evidence extraction under strict intent/entity lock constraints.",
        outputs=["media processing notes or asset instructions appended to the active artifact"],
        references=["Useful for evidence packaging and asset-heavy workflows.", "Should stay stateless and task-scoped."],
        next_steps=["entity-lock", "prompt-fidelity-check", "test-hub", "review-hub", "ux-structure"],
        mission="Handle media-specific steps that support the current lane without creating a parallel project.",
        tasks=[
            "Prepare screenshots or assets for evidence.",
            "Describe required transforms or formats with target IDs.",
            "Hand back what the next skill needs to continue.",
        ],
        rules=[
            "Keep transformations reversible when possible.",
            "Name exact asset sources, outputs, and allowed edit targets.",
            "Do not transform media before intent-lock and entity-lock are marked pass for edit lanes.",
        ],
    ),
    "prompt-fidelity-check": utility_provider_spec(
        name="prompt-fidelity-check",
        description="Use when the lane is close to completion and must prove delivered behavior matches the original request without drift.",
        outputs=[
            "asked-versus-delivered comparison notes appended to qa-report",
            "drift verdict pass or fail with evidence links appended to workflow-state or qa-report",
        ],
        references=[
            "No done verdict without a pass drift verdict for edit requests.",
            "Use intent-contract and entity-map as source of truth for comparisons.",
        ],
        next_steps=["qa-governor", "review-hub", "debug-hub", "workflow-router"],
        mission="Prevent ask-delivery drift by enforcing an explicit requested-versus-delivered comparison before completion.",
        tasks=[
            "Build a compact Asked vs Delivered table from intent-contract and produced evidence.",
            "Validate forbidden changes did not occur and allowed changes did occur.",
            "Write drift verdict pass or fail with specific evidence pointers.",
            "Route to debug-hub when verdict is fail or evidence is insufficient.",
        ],
        rules=[
            "No neutral verdict; result must be pass, fail, or hold with reason.",
            "A pass verdict requires fresh evidence, not inferred confidence.",
            "Keep checks scoped to current lane deliverables only.",
        ],
    ),
    "aesthetic": utility_provider_spec(
        name="aesthetic",
        description="Use when visual quality matters and output risks looking generic or AI-generated. Aesthetic direction utility for stronger hierarchy and composition.",
        outputs=[
            "design direction notes and taste controls appended to the active artifact",
            "screenshot critique findings with concrete hierarchy corrections",
        ],
        references=[
            "Reference-driven structure beats invented average structure.",
            "If the first pass looks generic, revise structure before polish.",
        ],
        next_steps=["frontend-design", "ui-styling", "brainstorm-hub", "plan-hub", "review-hub"],
        mission="Raise visual quality through explicit design direction, critique, and revision discipline.",
        tasks=[
            "Set design variance, motion intensity, and visual density before proposing UI changes.",
            "Identify focal point, hierarchy conflicts, and repeated template-like blocks.",
            "Route implementation-ready guidance to frontend-design or ui-styling.",
        ],
        rules=[
            "Do not approve generic three-card layouts without hierarchy intent.",
            "Use concrete references or screenshot evidence when suggesting visual changes.",
            "Keep recommendations tied to product goals and readability, not decoration.",
        ],
    ),
    "frontend-design": utility_provider_spec(
        name="frontend-design",
        description="Use when a lane needs to implement or refactor UI with clear visual direction and production-ready structure. Frontend design execution utility.",
        outputs=[
            "implementation-ready UI structure guidance appended to the active artifact",
            "state coverage notes for loading, empty, and error scenarios",
        ],
        references=[
            "Build from explicit design direction, not vague adjectives.",
            "Treat component libraries as ingredients, not final design.",
        ],
        next_steps=["ui-styling", "developer", "fix-hub", "test-hub", "review-hub"],
        mission="Convert UI intent into implementation-ready structure that remains distinctive and maintainable.",
        tasks=[
            "Define composition, hierarchy, and responsive behavior before coding details.",
            "Ensure loading, empty, and error states are included for real product surfaces.",
            "Call out where implementation should use shared components versus custom layout work.",
        ],
        rules=[
            "Avoid template-like safe layouts when hierarchy demands stronger composition.",
            "Prefer explicit section roles (dominant/supporting/quiet) over equal-weight blocks.",
            "Route accessibility and verification concerns back through test-hub and qa-governor.",
        ],
    ),
    "ui-styling": utility_provider_spec(
        name="ui-styling",
        description="Use when a lane needs styling system decisions, component theming, responsive polish, or design token consistency. UI styling utility.",
        outputs=[
            "styling-system recommendations appended to tech-spec, qa-report, or workflow-state",
            "component-level styling guardrails for consistency and accessibility",
        ],
        references=[
            "Style decisions should reinforce hierarchy and usability.",
            "Prefer consistent tokens over ad-hoc utility-class sprawl.",
        ],
        next_steps=["frontend-design", "fix-hub", "test-hub", "review-hub"],
        mission="Stabilize UI styling decisions so implementation stays cohesive across screens and adapters.",
        tasks=[
            "Define typography, spacing, color, and motion constraints for the active surface.",
            "Review component states for contrast, focus behavior, and responsive integrity.",
            "Recommend targeted style adjustments tied to concrete product states.",
        ],
        rules=[
            "Do not approve styling that hides weak hierarchy behind decorative gradients.",
            "Keep motion performance-safe and respect reduced-motion requirements.",
            "Tie every styling recommendation to a specific screen or component state.",
        ],
    ),
}
